name: autocareconnect
description: "Final Project"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  firebase_auth_web: ^5.8.1
  cloud_firestore: ^5.4.4
  geolocator: ^13.0.1
  google_maps_flutter: ^2.2.1
  cupertino_icons: ^1.0.8
  auto_route: ^9.2.2
  camera: ^0.11.0+2
  location: ^4.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.0.0
  auto_route_generator: ^9.0.0
  analyzer: ^6.7.0


flutter:
  uses-material-design: true
